#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------
wmakeLnInclude -u aggregate
wmakeLnInclude -u backgroundMesh

wmake $targetType aggregate
wmake $targetType backgroundMesh

#------------------------------------------------------------------------------
