#include "rectangularChannel.H"
#include "pointField.H"     // For Foam::pointField
#include "faceList.H"       // For Foam::faceList
#include "point.H"          // For Foam::point
#include "boundBox.H"       // For Foam::boundBox
#include "List.H"           // For Foam::List
#include "primitivePatch.H" // May be needed by geomObject or its usage
#include "error.H"          // For Foam::WarningIn, Foam::FatalErrorInFunction

namespace Bashyal
{

// --- Constructor ---

rectangularChannel::rectangularChannel()
:boundary(), // Call base class default constructor
  length_(2.0), // Default value
  width_(0.3),  // Default value
  height_(0.3), // Default value
  slope_(0.01)   // Default value
{
    // *** Initialize default patch types ***
    initializeDefaultPatchTypes();
    develop();
    generateNefPolyhedron(); // Generate Nef polyhedron if needed

    // Geometry (points_, faces_, boundBox_) is NOT generated by default.
    // User must call initialize() explicitly.
}


// --- Private Methods ---

void rectangularChannel::initializeDefaultPatchTypes()
{
    patchTypes_.setSize(6); // A rectangular prism always has 6 faces

    // Assign patch types based on face index order defined in develop()
    patchTypes_[0] = 10; // Face 0: Inlet (Front face, X-min)
    patchTypes_[1] = 11; // Face 1: Outlet (Back face, X-max)
    patchTypes_[2] = 13; // Face 2: Bottom face (Wall)
    patchTypes_[3] = 15; // Face 3: Top face (SymmetryPlane)
    patchTypes_[4] = 12; // Face 4: Left side face (Front/Back type)
    patchTypes_[5] = 12; // Face 5: Right side face (Front/Back type)
}

void rectangularChannel::develop()
{
    // Assumes length_, width_, height_, slope_ have been set by initialize()

    // --- Basic Validation ---
    if (length_ <= 0 || width_ <= 0 || height_ <= 0)
    {
        // Raise a warning but proceed - maybe default values were intended?
        WarningIn("rectangularChannel::develop()")
            << "Developing channel geometry with non-positive dimensions." << Foam::endl
            << "  Length: " << length_
            << ", Width: " << width_
            << ", Height: " << height_ << Foam::endl;
        // Or make it a FatalError if required:
        // Foam::FatalErrorInFunction
        //     << "Cannot develop channel geometry with non-positive dimensions."
        //     << Foam::exit(Foam::FatalError);
    }

    // --- Define the 8 vertices of the rectangular prism ---
    Foam::pointField points(8); // Allocate space for 8 points

    Foam::scalar halfWidth = width_ / 2.0;
    Foam::scalar zBackBottom = 0.0 - slope_ * length_; // Z at bottom back
    Foam::scalar zBackTop = height_ - slope_ * length_;   // Z at top back

    // Front face vertices (x = 0)
    points[0] = Foam::point(0.0, -halfWidth, 0.0);     // Front Bottom Left (FBL)
    points[1] = Foam::point(0.0,  halfWidth, 0.0);     // Front Bottom Right (FBR)
    points[2] = Foam::point(0.0,  halfWidth, height_); // Front Top Right (FTR)
    points[3] = Foam::point(0.0, -halfWidth, height_); // Front Top Left (FTL)

    // Back face vertices (x = length)
    points[4] = Foam::point(length_, -halfWidth, zBackBottom); // Back Bottom Left (BBL)
    points[5] = Foam::point(length_,  halfWidth, zBackBottom); // Back Bottom Right (BBR)
    points[6] = Foam::point(length_,  halfWidth, zBackTop);    // Back Top Right (BTR)
    points[7] = Foam::point(length_, -halfWidth, zBackTop);    // Back Top Left (BTL)

    // --- Define the 6 faces using vertex indices ---
    Foam::faceList faces(6); // Allocate space for 6 faces

    // Face 0: Front face (inlet, x=0 plane, normal pointing -X) -> patchType 10
    faces[0] = Foam::face({0, 1, 2, 3});
    // Face 1: Back face (outlet, x=length plane, normal pointing +X) -> patchType 11
    faces[1] = Foam::face({4, 5, 6, 7});
    // Face 2: Bottom face (z=0 / sloped plane, normal pointing -Z) -> patchType 13
    faces[2] = Foam::face({0, 4, 5, 1});
    // Face 3: Top face (z=height / sloped plane, normal pointing +Z) -> patchType 15
    faces[3] = Foam::face({3, 2, 6, 7});
    // Face 4: Left side face (y=-width/2 plane, normal pointing -Y) -> patchType 12
    faces[4] = Foam::face({0, 3, 7, 4});
    // Face 5: Right side face (y=+width/2 plane, normal pointing +Y) -> patchType 12
    faces[5] = Foam::face({1, 5, 6, 2});

    // Assign to base class
    *static_cast<Foam::particleModels::indexedFaceSet*>(this) = Foam::particleModels::indexedFaceSet(points, faces);
}


// --- Public Member Functions ---

void rectangularChannel::initialize(
    Foam::scalar length,
    Foam::scalar width,
    Foam::scalar height,
    Foam::scalar slope
)
{
    // Store the parameters
    length_ = length;
    width_ = width;
    height_ = height;
    slope_ = slope;

    // Call develop to generate geometry based on the new parameters
    develop();

    // Optional: Set the name of the geometry object if geomObject supports it
    // this->name() = "rectangularChannel"; // If name() returns a non-const reference
}


// --- Accessor Implementations ---

// *** Implement the getter for patchTypes_ ***
const Foam::List<int>& rectangularChannel::getPatchTypes() const
{
    // No check needed here as it's initialized in the constructor
    return patchTypes_;
}


} // End namespace Bashyal
