#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------
wmakeLnInclude -u geomObject
wmakeLnInclude -u boundary

wmake $targetType geomObject
wmake $targetType boundary

#------------------------------------------------------------------------------
