#ifndef quickMesh_H
#define quickMesh_H

#include "point.H"       // For point class (coordinate representation)
#include "boundBox.H"    // For boundBox class (bounding box structure)
#include "pointField.H"  // For pointField class (list of points)
#include "faceList.H"    // For faceList class (list of faces)

#include "label.H"       // For label type
#include "labelList.H"

#include "wordList.H"


#include "cellList.H"
#include "polyMesh.H"
#include "IOobject.H"

#include "HashSet.H"


#endif

