#ifndef quickInclude_H
#define quickInclude_H

#include "Time.H"
#include "argList.H"

#include "point.H"
#include "pointField.H"
#include "faceList.H"
#include "List.H"
#include "DynamicList.H"

#include "scalar.H"
#include "labelList.H"
#include "wordList.H"
// #include "vector.H"
#include "tensor.H"
#include "Random.H"
#include "Vector.H"


#include "transform.H"
#include "dictionary.H"
#include "IOdictionary.H"


#endif

// ************************************************************************* //