# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   
PKG_PATH =  
PKG_LIB =   

PKG_SYSINC =  $(voronoi_SYSINC) 
PKG_SYSLIB =  $(voronoi_SYSLIB) 
PKG_SYSPATH = $(voronoi_SYSPATH) 
